## Подключение модулей и библиотек
Для получения дополнительного инструментария (не содержащегося в стандартном Python) можно подключать дополнительные модули Python и разные библиотеки.

## Модули
Модуль содержит некоторые функции и данные в отдельном файле.   
   
>  **<имя файла>  =  <имя модуля>.py**

### Импорт модуля:


> **import <имя модуля>**

Например:

In [1]:
import math

### Обращение к функции, описанной в модуле:


> **<имя модуля>.<имя функции>(<параметры>)**

Например:

In [2]:
i = 5
print(math.factorial(i))

120


### Импорт отдельных функций из модуля:


> **from <имя модуля> import <имя функции>**

В таком случае при последующем обращении к данной функции имя модуля не указывается.

Например:

In [3]:
from math import floor, ceil
t = 1.768
print("Округление до ближайшего бОльшего целого:", ceil(t))
print("Округление до ближайшего меньшего целого:", floor(t))

Округление до ближайшего бОльшего целого: 2
Округление до ближайшего меньшего целого: 1


### Импорт всех функций и данных из модуля:


>  from <имя модуля> import *  


При последующих обращениях к функциям имя модуля не указывается.

### Импорт функции из модуля с заменой названия функции в вызывающей программе:


> **from <имя модуля> import <имя функции в модуле> as <псевдоним>**

Например:

In [4]:
from math import factorial as fact
n = 5
print(fact(n))

120


[Описание библиотеки стандартных модулей Python 3](https://docs.python.org/3/library).

### Примеры стандартных модулей Python:
#### **модуль math**
   Содержит основные математические функции (экспонента, логарифмы, тригонометрия и т. д.).  
#### **модуль sys**
  Содержит системные функции.    
  Например: sys.argv - список (объект list) аргументов командной строки.
  
  Вывод списка параметров, с которыми запущена программа:

In [5]:
import sys
print(sys.argv)

['/usr/local/lib/python3.11/dist-packages/colab_kernel_launcher.py', '-f', '/root/.local/share/jupyter/runtime/kernel-bccbe791-caad-467b-b834-55bc3f2fda7b.json']


#### **модуль subprocess**
  Содержит инструменты запуска внешних процессов.

# Библиотеки
### Подключение библиотеки:

> **import <имя библиотеки> as <псевдоним>**

После этого доступны функции и методы, реализованные в библиотеке.   
### Обращение к функции:   


> **<имя библиотеки>.<имя функции>(<параметры>)**


Некоторые функции и данные в библиотеке могут быть сгруппированы в модули (в составе этой библиотеки).   
### Обращение к функции из модуля библиотеки:   


> **<имя библиотеки>.<имя модуля>.<имя функции>(<параметры>)**


## Библиотека NumPy
[Официальный сайт библиотеки](https://numpy.org/)

[Руководство пользователя](https://numpy.org/doc/stable/user/index.html#user)

Основной тип данных - массивы (ndarray).

Их отличие от списков: массивы могут содержать данные только **одного типа**.

### Создание массива (из списка элементов):


> import numpy as np

> <имя массива> = np.array([элемент 1, элемент 2, ... ])

Элементами массива могут быть другие массивы. Так формируются многомерные массивы.

### Преобразование существующего списка в массив NumPy:

> <имя массива> = np.array(<имя списка>)

### Преобразование массива в список:

> <имя списка> = list(<имя объекта>)

In [6]:
import numpy as np
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [7]:
print(a)

[2 3 4]


In [8]:
x = [1, 3, 5, 7]  # список
print('Тип первоначально созданного объекта:')
print(type(x), x)
y = np.array(x)   # преобразование списка в массив numpy
z = list(y)  # преобразование массива numpy в список
print('Типы преобразованных объектов:')
print('y ', type(y), y)
print('z ', type(z), z)

Тип первоначально созданного объекта:
<class 'list'> [1, 3, 5, 7]
Типы преобразованных объектов:
y  <class 'numpy.ndarray'> [1 3 5 7]
z  <class 'list'> [1, 3, 5, 7]


## Работа с массивами
### Определение числа измерений массива:

> <имя массива>.ndim

### Определение размерности массива (число элементов по каждому измерению):

> <имя массива>.shape

### Определение общего количества элементов массива:

> <имя массива>.size

**!!!** При разном количестве элементов вложенных массивов данный массив будет рассматриваться как одномерный (его элементы - массивы 2-го уровня, преобразованные в списки). В версиях библиотеки, более поздних, чем 1.21, в таких случаях требуется дополнительно определять параметр dtype = object, чтобы не возникала ошибка.

In [9]:
print(a) # для напоминания (масссив a был определен выше)
print('Количество измерений массива', a.ndim)
print('Размерность массива', a.shape)
print('Количество элементов массива', a.size)

[2 3 4]
Количество измерений массива 1
Размерность массива (3,)
Количество элементов массива 3


In [10]:
b = np.array([[1.2, 2, 5, -1], [3, 4.1, -2, 7]])
print(b)
print('Количество измерений массива', b.ndim)
print('Размерность массива', b.shape)
print('Количество элементов массива', b.size)

[[ 1.2  2.   5.  -1. ]
 [ 3.   4.1 -2.   7. ]]
Количество измерений массива 2
Размерность массива (2, 4)
Количество элементов массива 8


In [11]:
#  Определение массива с разным числом элементов во вложенных массивах (массивах 2-го уровня)
c = np.array([[1.2, 2, 5], [3, 4.1]], dtype = object)
print(c)
print('Количество измерений массива', c.ndim)
print('Размерность массива', c.shape)
print('Количество элементов массива', c.size)

[list([1.2, 2, 5]) list([3, 4.1])]
Количество измерений массива 1
Размерность массива (2,)
Количество элементов массива 2


Обращение к элементам массива - по индексам.

С индексами возможны все манипуляции, которые доступны для списков.  
   
Дополнительно:
- в многомерном массиве можно указывать индексы перечислением в одних квадратных скобках (в списках так нельзя):   
    <имя массива>[<индекс 1>, <индекс 2>]
- допускается логическая индексация (индексом является логическое выражение).

In [12]:
print(y)
print(y[::2]) # вывод всех элементов массива через 1
print(y[0], y[-1]) # вывод первого и последнего элементов массива
print(y[[0, 2, -1]]) # вывод элементов массива по списку их индексов
print(y[y>3]) # вывод всех элементов массива, больших 3

[1 3 5 7]
[1 5]
1 7
[1 5 7]
[5 7]


In [13]:
# b - массив
print(b)
print('b[1, 2] = ', b[1, 2])
B = [[1, 2, 3], [2, -3, 4]]  # список, а не массив
# Для списка так не работает (будет ошибка)
# print(B[1, 2])

[[ 1.2  2.   5.  -1. ]
 [ 3.   4.1 -2.   7. ]]
b[1, 2] =  -2.0


### Другие отличия от списков
#### Операция умножение на число ("*")
- в списках - дублирование списка
- в массивах - умножение на это число каждого элемента массива (количество элементов массива не изменяется)

#### Применение других арифметических операций и математических функций  
- к спискам - не работает (можно применять только к отдельным элементам списков)
- к массиву - описание ниже.   

#### Операции " + " и " - "
> к массивам применяются поэлементно.

#### Операция " ** " (возведение массива в степень)
> применяется поэлементно - все элементы массива возводятся в данную степень.

#### Применение математических функций:
> массив можно указывать в качестве аргумента функции (exp(), sin(), cos() и т. п.). Функция будет применена к каждому элементу массива отдельно.

#### Применение к массиву операций сравнения:
> результат - массив булевских значений (результат поэлементного применения операции сравнения).

In [14]:
x = [1, 3, 5, 7]  # список
y1 = np.array(x)   # преобразование в массив numpy
y2 = np.array([2, 4, 6, 8])
print('x =', x)
print('y1 =', y1)
print('y2 =', y2)
print("Умножение списка на число: x*3 = ", x*3)
print("Умножение массива на число: y1*3 = ", y1*3)
print("Сложение массивов: y1+y2 = ", y1+y2)
print("Вычитание массивов: y1-y2 = ", y1-y2)
print("Возведение массива в степень: y1**2 = ", y1**2)
print("Применение к массиву y1 функции sin(): ", np.sin(y1))
print("Проверка условия 'элемент массива y1 больше 3': ", y1>3)
# аналогичные операции для списков не работают (будет ошибка)
# print(x**2)
# print(x>3)

x = [1, 3, 5, 7]
y1 = [1 3 5 7]
y2 = [2 4 6 8]
Умножение списка на число: x*3 =  [1, 3, 5, 7, 1, 3, 5, 7, 1, 3, 5, 7]
Умножение массива на число: y1*3 =  [ 3  9 15 21]
Сложение массивов: y1+y2 =  [ 3  7 11 15]
Вычитание массивов: y1-y2 =  [-1 -1 -1 -1]
Возведение массива в степень: y1**2 =  [ 1  9 25 49]
Применение к массиву y1 функции sin():  [ 0.84147098  0.14112001 -0.95892427  0.6569866 ]
Проверка условия 'элемент массива y1 больше 3':  [False False  True  True]


### Генерация массивов
#### Создание массива из нулей:

> **<имя массива> = np.zeros(перечисление - количество элементов в измерениях)**

#### Создание массива из единиц:

> **<имя массива> = np.ones(перечисление - количество элементов в измерениях)**


In [15]:
zers = np.zeros(5)
ons = np.ones((3, 2))
print(zers)
print(ons)

[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### Создание единичной матрицы:

> **<имя массива> = np.eye(порядок матрицы)**

In [16]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### Генерация с помощью функции **arange()**:

> **<имя массива> = np.arange(<начальное значение>, <конечное значение>, <шаг>)**

   Аргументы функции определяются так же, как у range().

#### Генерация с помощью функции **linspace()**:

>**<имя массива> = np.linspace(<левый конец интервала>, <правый конец интервала>, <количество генерируемых точек>)**

Эта функция удобна для генерации массивов нецелых значений (например, при построении графиков).   
  
**!!!** Отличие linspace() от range() и arange(): правый конец интервала включается.

In [17]:
x1 = np.arange(10)
print(x1)
x2 = np.arange(0, 10, 2)
print(x2)
x3 = np.linspace(0, 10, 11)
print(x3)
x4 = np.linspace(-1, 5, 13)
print(x4)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[-1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5. ]


#### Генерация массивов с элементами - псевдослучайными числами.

С помощью функции **rand()** из модуля **random** (в составе NumPy):

> **<имя массива> = np.random.rand(количество элементов в каждом измерении)**

[Документация функции](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

Если требуется при нескольких запусках получать одну и ту же псевдослучайную последовательность (например, в процессе отладки), то следует зафиксировать экземпляр генератора:


> **np.random.seed(номер генератора)**




In [18]:
# Запустите ячейку несколько раз, чтобы убедиться, что при каждом запуске формируется новая матрица
rand_matrix = np.random.rand(3, 4)
print(rand_matrix)

[[0.14639257 0.41029489 0.92913181 0.11549984]
 [0.50378911 0.5422946  0.96988342 0.43562603]
 [0.86373937 0.8225294  0.51244045 0.8391681 ]]


In [19]:
# Запустите ячейку несколько раз, чтобы убедиться, что при каждом запуске формируется одна и та же матрица
# потом измените номер генератора
i = 5
np.random.seed(i)
rand_matrix = np.random.rand(3, 4)
print(rand_matrix)

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]
 [0.2968005  0.18772123 0.08074127 0.7384403 ]]


### Изменение размерности массивов
#### Получение одномерного вектора из многомерного массива ("вытягивание" в одну строку):

> **<имя массива>.ravel()**

#### Преобразование в массив заданной размерности:

> **<имя массива>.reshape(количество элементов по измерениям)**

По умолчанию элементы располагаются "по строкам" (сначала изменяется последний индекс").

[Документация функции](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

In [20]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]]) # Создание двумерного массива
print('Первоначальная матрица: \n', matrix1)
print('Размерность:', matrix1.shape)
vect = matrix1.ravel() # преобразование в одномерный вектор
print('\nПреобразование в одномерный вектор: \n', vect)
print('Размерность:', vect.shape)
matrix2 = vect.reshape(2, 3) # преобразование к первоначалной размерности
print('\nПреобразование к первоначальной размерности: \n', matrix2)
print('Размерность:', matrix2.shape)
matrix3 = matrix2.reshape(3, 2) # преобразование к другой размерности
print('\nПреобразование к другой размерности: \n', matrix3)
print('Размерность:', matrix3.shape)

Первоначальная матрица: 
 [[1 2 3]
 [4 5 6]]
Размерность: (2, 3)

Преобразование в одномерный вектор: 
 [1 2 3 4 5 6]
Размерность: (6,)

Преобразование к первоначальной размерности: 
 [[1 2 3]
 [4 5 6]]
Размерность: (2, 3)

Преобразование к другой размерности: 
 [[1 2]
 [3 4]
 [5 6]]
Размерность: (3, 2)


Если в аргументах reshape() по одной из осей указать -1, то количество элементов по этому измерению будет рассчитано программно.
То же - относительно ravel().

In [21]:
matrix4 = matrix2.reshape(3, -1) # преобразование к другой размерности с расчетом количества элементов по второй оси
print(matrix4)
print(matrix4.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


### Матричные операции над массивами
#### Матричное умножение (по правилу "строка на столбец"):

> **<Первый множитель>.dot(<Второй множитель>)**

либо:

> **np.dot(<Первый множитель>, <Второй множитель>)**

либо:

> **<Первый множитель> @ <Второй множитель>**

In [22]:
A = np.random.rand(2, 4)
B = np.random.rand(4, 1)
print("A = ", A)
print("B = ", B)
C1 = A.dot(B)
print("\nAB первым способом: \n", C1)
C2 = np.dot(A, B)
print("AB вторым способом: \n", C2)
C3 = A @ B
print("AB третьим способом: \n", C3)

A =  [[0.44130922 0.15830987 0.87993703 0.27408646]
 [0.41423502 0.29607993 0.62878791 0.57983781]]
B =  [[0.5999292 ]
 [0.26581912]
 [0.28468588]
 [0.25358821]]

AB первым способом: 
 [[0.62684682]
 [0.65326246]]
AB вторым способом: 
 [[0.62684682]
 [0.65326246]]
AB третьим способом: 
 [[0.62684682]
 [0.65326246]]


#### Вычисление определителя квадратной матрицы.

Функция det() из модуля linalg (в составе NumPy):

> **np.linalg.det(<имя массива>)**

[Документация функции](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det)

#### Вычисление обратной матрицы (для квадратной невырожденной матрицы).

Функция inv() из модуля linalg:

> **np.linalg.inv(<имя массива>)**

[Документация функции](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv)

In [23]:
A1 = np.array([[1, 2, -3], [4, -5, 6], [-7, 8, 9]])
print("A1 = ", A1)
print("Определитель A1 = ", np.linalg.det(A1))
A_inv = np.linalg.inv(A1)
print("A_inv = ", A_inv)
print("\nПроверка : \n", A1 @ A_inv)

A1 =  [[ 1  2 -3]
 [ 4 -5  6]
 [-7  8  9]]
Определитель A1 =  -240.0000000000002
A_inv =  [[0.3875     0.175      0.0125    ]
 [0.325      0.05       0.075     ]
 [0.0125     0.09166667 0.05416667]]

Проверка : 
 [[ 1.00000000e+00  0.00000000e+00 -2.08166817e-17]
 [ 9.02056208e-17  1.00000000e+00  9.71445147e-17]
 [ 2.46330734e-16  1.11022302e-16  1.00000000e+00]]


#### Применение агрегатных функций
(вычисление суммы элементов, определение максимального/минимального элемента, определение статистических характеристик).

Функции **np.sum()**, **np.max()**, **np.min()** и др.

> **np.<имя функции>(<имя массива>, <измерение>, ...)**

Измерение, по которому нужно выполнить операцию (просуммировать, найти максимум/минимум, ...) указывается с помощью параметра **axis**. Определяет, какая оси (оси) фиксируются при выполнении операции.

Для двумерных массивов:

*   axis=1  - выполнение операции по строкам (фиксируются номера столбцов);
*   axis=0  - выполнение операции по столбцам (фиксируются номера строк);
*   axis=None (по умолчанию)  - выполнение операции по всему массиву.


[Документация функции sum()](https://numpy.org/doc/stable/reference/generated/numpy.sum.html)

[Документация функции max()](https://numpy.org/doc/stable/reference/generated/numpy.max.html)

[Документация функции min()](https://numpy.org/doc/stable/reference/generated/numpy.min.html#numpy.min)

Определение индекса максимального/минимального элемента массива (по измерению): функции **argmax()**, **argmin()**

[Документация argmax()](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html#numpy.argmax)

[Документация argmin()](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin)

In [24]:
print("A1 = \n", A1)
print("Максимумы по столбцам: ", np.max(A1, axis=0))
print("Индексы максимальных элементов: ", np.argmax(A1, axis=0))
print("Сумма всех элементов матрицы: ", np.sum(A1))

A1 = 
 [[ 1  2 -3]
 [ 4 -5  6]
 [-7  8  9]]
Максимумы по столбцам:  [4 8 9]
Индексы максимальных элементов:  [1 2 2]
Сумма всех элементов матрицы:  15


### Объединение массивов
#### По строкам (функция vstack()):

> **np.vstack((<первый массив>, <второй массив>))**

#### по столбцам (функция hstack()):

> **np.hstack((<первый массив>, <второй массив>))**


[Документация функции vstack](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html)

[Документация функции hstack](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html)

#### Более общий функционал обеспечивает функция np.concatenate():

> **np.concatenate((<первый массив>, <второй массив>, <измерение>, ...))**

Ось, вдоль которой нужно выполнить объединение, указывается с помощью параметра **axis**.

[Документация функции concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate)

In [25]:
# Применение vstack и hstack
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Первый массив: \n", arr1, arr1.shape)
arr2 = np.array([7, 8, 9]).reshape(1, 3)  # reshape преобразует размерность (3,) в размерность (1, 3)
print("Второй массив: \n", arr2, arr2.shape)
print("Объединение по строкам: \n", np.vstack((arr1, arr2)))
print("\nПервый массив: \n", arr1, arr1.shape)
arr3 = np.array([7, 8]).reshape(2, 1)  # reshape преобразует размерность (2,) в размерность (2, 1)
print("Второй массив: \n", arr3, arr3.shape)
print("Объединение по столбцам: \n", np.hstack((arr1, arr3)))

Первый массив: 
 [[1 2 3]
 [4 5 6]] (2, 3)
Второй массив: 
 [[7 8 9]] (1, 3)
Объединение по строкам: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Первый массив: 
 [[1 2 3]
 [4 5 6]] (2, 3)
Второй массив: 
 [[7]
 [8]] (2, 1)
Объединение по столбцам: 
 [[1 2 3 7]
 [4 5 6 8]]


In [26]:
# Применение concatenate
print("Первый массив: \n", arr1, arr1.shape)
print("Второй массив: \n", arr2, arr2.shape)
print("Объединение по строкам: \n", np.concatenate((arr1, arr2), axis=0))
print("\nПервый массив: \n", arr1, arr1.shape)
print("Второй массив: \n", arr3, arr3.shape)
print("Объединение по столбцам: \n", np.concatenate((arr1, arr3), axis=1))

Первый массив: 
 [[1 2 3]
 [4 5 6]] (2, 3)
Второй массив: 
 [[7 8 9]] (1, 3)
Объединение по строкам: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Первый массив: 
 [[1 2 3]
 [4 5 6]] (2, 3)
Второй массив: 
 [[7]
 [8]] (2, 1)
Объединение по столбцам: 
 [[1 2 3 7]
 [4 5 6 8]]


### Применение функции zip()
Эта функция позволяет сформировать из нескольких массивов единый объект - итерируемый набор кортежей.

> **zip(<первый массив>, <второй массив>, ...)**

[Документация функции zip](https://docs.python.org/3/library/functions.html#zip)

Вывести содержимое объекта zip напрямую нельзя. Нужно предварительно преобразовать его в список или массив

**Пример**: формирование набора троек вида (<первый множитель>, <второй множитель>, <произведение>), где множители являются элементами заданных массивов

In [27]:
a = np.arange(1, 11)                     # массив чисел - первые множители
b = np.arange(5, 15)                     # массив чисел - вторые множители
ab = a*b                                 # массив из произведений

triples = zip(a, b, ab)                  # формирование объекта zip (набора кортежей указанного вида)
print(type(triples))

lst = [triple for triple in triples]     # формирование списка кортежей из объекта zip
print(lst)

<class 'zip'>
[(1, 5, 5), (2, 6, 12), (3, 7, 21), (4, 8, 32), (5, 9, 45), (6, 10, 60), (7, 11, 77), (8, 12, 96), (9, 13, 117), (10, 14, 140)]


## Библиотека Scipy
Содержит инструментарий высокоуровневых математических вычислений:
- средства линейной алгебры (решение систем линейных уравнений, матричные разложения и т. д.) - модуль **linalg**;
- методы оптимизации (методы градинтного спуска в разных вариантах, методы оптимизации недифференцируемых функций и т. д.) - модуль **optimize**;
- методы статистической обработки данных - модуль **stats**;
- и др.

[Официальный сайт библиотеки](https://scipy.org/)

[Руководство пользователя](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide)

### Нахождение экстремумов функций - модуль **optimize**
#### Импорт модуля:

> **from scipy import optimize as <псевдоним>**

#### Импорт только некоторых функций модуля:


> **from scipy.optimize import <список имен функций>**

#### Нахождение точки минимума функции - метод minimize():

> **minimize(<имя функции>, <начальная точка>, ... )**


Минимизируемая функция может быть функцией многих переменных (аргумент - массив numpy).
Среди необязательных параметров метода **minimize**:
- метод минимизации (по умолчанию - один из методов градиентного спуска);
- методы вычисления градиента, матрицы Гессе (матрицы из вторых частных производных);
- другие параметры, определяющие работу алгоритма построения последовательности значений, сходящихся (?) к точке минимума.

Функция возвращает объект OptimizeResult, содержащий информацию о найденной точке минимума (координаты, значение функции в этой точке, вектор градиента и др.), число выполненных итераций, сообщение об успешности работы алгоритма и т. п.

[Документация функции](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html)

In [28]:
from scipy import optimize as opt

# Определение минимизируемой функции
def f(x):
    return x**4+4*x**3+6*x**2+4*x+1

x_min = opt.minimize(f, 5)
print(x_min)  # вывод информации о результатах оптимизации

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 3.054277897263091e-08
        x: [-9.868e-01]
      nit: 22
      jac: [ 9.209e-06]
 hess_inv: [[ 1.998e+02]]
     nfev: 46
     njev: 23


In [29]:
# Вывод только точки минимума
print('x_min: ', x_min.x)
print('f_min: ', x_min.fun)

x_min:  [-0.98678013]
f_min:  3.054277897263091e-08


In [30]:
# Иллюстрация возможных проблем
# Минимизируемая функция не дифференцируема в точке минимума

import math
def g(x):
    return abs(x)

x_min = opt.minimize(g, 5)
print(x_min)

  message: Desired error not necessarily achieved due to precision loss.
  success: False
   status: 2
      fun: 6.28864782470373e-09
        x: [-6.289e-09]
      nit: 1
      jac: [ 1.560e-01]
 hess_inv: [[ 5.924e+00]]
     nfev: 136
     njev: 62
